# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yYRRXxL_Ic8rhpGpLltog4wBb6d4zCk
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile TourismPrediction.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run TourismPrediction.py & npx localtunnel --port 8501